
AllCops:
  Excludes:
    - db/**
    - config/**
    - script/**
    - bin/**
    - node_modules/**/**
    - lib/tasks/**

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/**